### ISSUE TITLE
Problem with bootstrap js when starting the server

### ISSUE THREAD

**Issue by paddleman** [lifegadget/ember-cli-bootstrap-sassy#1] opened 2015-02-01 04:50 UTC
I am getting this error when I attempt to start the server.

Path or pattern "bower_components/bootstrap-sass-official/assets/javascripts/bootstrap.js" did not match any files.

ignoring the bootstrap javascript in the Brocfile does not resolve the issue.

Using 
ember-cli 0.1.12
ember1.10-beta4
ember-data1.0.0-beta14.1

The server worked without errors with this setup and ember-cli-sass installed.  It errored once I install ember-cli-bootstrap-sassy.

**Comment by yankeeinlondon** [comment] 2015-02-01 10:48
Sorry I released this last night a little tired; I'll look into it. Should be pretty easy to get working this morning.

**Comment by yankeeinlondon** [comment] 2015-02-01 12:22
It should work now but please completely uninstall both Bootstrap and Sassy before reinstalling. 

```
// uninstall
bower uninstall --save bootstrap-sass-official
npm uninstall --save-dev ember-cli-bootstrap-sassy
// re-install
ember install:addon ember-cli-bootstrap-sassy
```

This should install Bootstrap _and_ the appropriate config to get it included. The one thing I'm still scratching my head over is the sequence that ember-cli uses in a build ... I suspect that if ember-cli-sass were executed _before_ sassy then the configuration might not have had a chance to be set yet. This would have been true in the original "bootstrap-sass" addon too though. 

In either case it does appear to work for me. Let me know if we can close this.

**Comment by akisvolanis** [comment] 2015-02-01 13:59
i have the same error too.

**Comment by yankeeinlondon** [comment] 2015-02-01 14:39
Can you guys check ... I think what's happening is the underlying bootstrap is not getting installed when you call `ember install:addon`. Do you have `bower_components/bootstrap-sass-official` directory?

I would expect it to install due to my blueprint here: [ember-cli-bootstrap-sassy](https://github.com/lifegadget/ember-cli-bootstrap-sassy/blob/master/blueprints/ember-cli-boostrap-sassy/index.js) but for some reason I don't think it's firing.

**Comment by yankeeinlondon** [comment] 2015-02-01 14:41
Oh shit. Typo. I have the blueprint in the "boostrap" directory. Errgh. Fix in 5 minutes.

**Comment by akisvolanis** [comment] 2015-02-01 16:53
seems it works now. But i'm getting this error while importing bootstrap "/tmp/tree_merger-tmp_dest_dir-H8kKD02r.tmp/app/styles/app.scss:1: file to import not found or unreadable: "bootstrap". I have to include the full path for _bootstrap.scss in order to work: @import "bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap";.

**Comment by yankeeinlondon** [comment] 2015-02-01 19:50
@charlatan154 hmmm ... any chance you could post an example of this so I can take a look? Secondarily, do you know anything about the sequencing of the the build pipeline? Specifically I'm wondering if maybe ember-cli-sass is being run before sassy's able to add the config parameters to it. I wouldn't have thought so but it's working as its supposed to for me.

Last point, please try and remove both and reinstall both if you haven't already. Sorry about that.

**Comment by yankeeinlondon** [comment] 2015-02-01 19:52
Oh, just in case, are you using the latest build? `v0.0.9`

**Comment by akisvolanis** [comment] 2015-02-02 08:57
Yes i'm using your latest build. I guess this error is because you haven't included the paths for ember-cli-sass in your config like : 

``` javascript
var app = new EmberApp({
  sassOptions: {
    includePaths: [
      'bower_components/bootstrap-sass-official/assets/stylesheets',
      'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap',
      'bower_components/bootstrap-sass-official/assets/stylesheets/bootstrap/mixins'
    ]
  }
});
```

One tip here, when you setup your addon sassOptions remember to extend the user's ones otherwise you'll overwrite them causing a headache to user :) something like this:

``` javascript
app.options.sassOptions = app.options.sassOptions || {};
app.options.sassOptions.includePaths = app.options.sassOptions.includePaths || [];
//then include your paths....
```

**Comment by akisvolanis** [comment] 2015-02-02 09:02
oh sorry i just saw that you actually include those paths. sorry :) i'll try some tests later and i'll come back if i found something...

**Comment by yankeeinlondon** [comment] 2015-02-02 09:24
@charlatan154 wrt to non-destructive configuration to sassOptions ... it was my PR which fixed this 6-9 months ago (that code sample you put in was my contribution) on the original bootstrap-sass :) Nice to see it show up again. 

I needed this because I tend to mix in Bourbon with my projects (the library not the liquor).

**Comment by akisvolanis** [comment] 2015-02-02 09:27
Yes i remember that cause i had this problem too. It's something you can't easy forget if you meet this once.. :) so thanks again :)

**Comment by akisvolanis** [comment] 2015-02-02 11:57
ok i found the issue. The broccili-sass compiler that i was using was causing the error. I thing it has to do with the handlebars version that i'm using ( v2.0 ). I switch to ember-cli-sass and everything works fine.

**Comment by yankeeinlondon** [comment] 2015-02-02 16:33
@charlatan154 ok, shall i close this issue?

**Comment by akisvolanis** [comment] 2015-02-02 16:39
yes i think it's ok. Thanks again...

**Closed as completed** 2015-02-02 16:46 UTC

**Comment by ballPointPenguin** [comment] 2015-02-19 08:15
I'm having the same problem with a fresh ember-cli app after running:

```
npm install --save-dev ember-cli-sass
ember install:addon ember-cli-bootstrap-sassy
rm app/styles/app.css
echo '@import "bootstrap";' > app/styles/app.scss
```

ember-cli 0.2.0-beta.1
iojs 1.2.0
npm 2.1.8

> > file to import not found or unreadable: bootstrap

**Comment by ballPointPenguin** [comment] 2015-02-19 08:19
Workaround (which I really don't mind) is to include the full bower_components/... path to bootstrap in my app.scss file.

I wonder if new addon loading stuff in ember-cli 0.2.0 is the cause of this regression.

**Comment by yankeeinlondon** [comment] 2015-02-19 08:26
Strange. I just brought this addon into a new project yesterday and it worked fine (0.1.15, node 0.10.33). Admittedly I'm not quite out as far on the _precipice_ as you with a ember-cli beta and io.js. I sort of suspect there might be a regression with 0.2.0 of CLI as the error would indicate that one of the broccoli build steps that the addon is meant to add is not being fired?

**Comment by dxmo** [comment] 2015-02-19 18:55
I can confirm this happens for me too with 0.2.0 beta. Apparently the 0.2.0 has some breaking changes for addons: https://github.com/ember-cli/ember-cli/blob/master/CHANGELOG.md

**Comment by yankeeinlondon** [comment] 2015-02-20 18:11
it'll take me a few days before I start switching to 0.2.0 but apparently there are mechanisms to support both old and new if either of you want to do the PR i'm happy to accept it.
