### ISSUE TITLE
Glyphicons showing up as emoticons

### ISSUE THREAD

**Issue by erichaus** [lifegadget/ember-cli-bootstrap-sassy#25] opened 2015-06-19 17:14 UTC
Hello,

I recently discovered that the glyphicons dont seem to be loading anymore and show as emoticons on ios.. Not sure what changed that made this happen but also no idea how to fix!

Any suggestions? Im using this repo + bootstrap-sass-official 3.3.5

**Comment by yankeeinlondon** [comment] 2015-06-22 15:16
@erichonkanen are you setting the configuration to something other than the default? By default it should load the fonts for glypicons: https://github.com/lifegadget/ember-cli-bootstrap-sassy/blob/master/index.js#L38-L45

**Comment by erichaus** [comment] 2015-06-22 17:50
@ksnyde

I've been loading them via my Brocfile:

```
/* global require, module */

var EmberApp = require('ember-cli/lib/broccoli/ember-app');

var app = new EmberApp();

// Use `app.import` to add additional libraries to the generated
// output files.
//
// If you need to use different assets in different
// environments, specify an object as the first parameter. That
// object's keys should be the environment name and the values
// should be the asset to use in that environment.
//
// If the library that you are including contains AMD or ES6
// modules that you would like to import into your application
// please specify an object with the list of modules as keys
// along with the exports of each module as its value.

// Bootstrap
app.import('bower_components/bootstrap-sass-official/assets/javascripts/bootstrap.js');
app.import('bower_components/bootstrap-sass-official/assets/fonts/bootstrap/glyphicons-halflings-regular.woff2', {
  destDir: 'fonts/bootstrap/'
});

// Slideout.js
app.import('bower_components/slideout.js/dist/slideout.min.js');

// Modernizr
app.import('vendor/modernizr.js');

module.exports = app.toTree();
```

**Comment by erichaus** [comment] 2015-06-22 17:53
seems like changing back to `0.0.12` from `0.0.18` works

**Comment by kulpae** [comment] 2015-06-25 10:39
Updating to ember-cli-sass 4.0.1 fixed that problem for me. (I had 3.3.0)
Latest bootstrap utilizes the '@at-root' directive which came with sass 3.3, but had a bug with '@font-face' until 3.3.4.

**Comment by yankeeinlondon** [comment] 2015-06-25 12:04
Ahh great. I'll get this updated over the next day or two (on the road at the moment).

**Comment by erichaus** [comment] 2015-06-25 16:05
I'm still having issues.. can you guys clarify which bower and npm packages I need to use this?

So far I have tried via bower: [bootstrap-sass](https://github.com/twbs/bootstrap-sass), and bootstrap-sass-official (is that the same lib? cant find it on git now)

Then in npm there is this package as well as ember-cli-sass. What about brocolli-sass which ive also seen?

Ive confirmed that everything works fine with version 0.0.12 of this and 0.3.4 of bootstrap-sass-official.

**Comment by yankeeinlondon** [comment] 2015-07-21 13:44
`bootstrap-sass-official` is the old repo name but they are functionally mirrors of each other; better to use `bootstrap-sass` now though.

**Comment by yankeeinlondon** [comment] 2015-07-21 13:46
You should include `ember-cli-sass@4.0.1` to get SASS into your project, this is a dependency for Bootstrap SASS to work for you.

**Comment by elidupuis** [comment] 2015-07-24 22:01
I've updated to `ember-cli-sass@4.0.1` and Bootstrap is being compiled properly now (I can see the Glyphicon files being requested). The problem now is that it's looking in `/assets/fonts` but the actual font files are placed in `/fonts` (this is all inside the `/dist` folder, obviously).

Is there configuration for this?

**Comment by elidupuis** [comment] 2015-07-24 22:14
Actually, it looks like the issue is that the font files are placed in `/assets/fonts/bootstrap/` but the CSS is just pointing to `/assets/fonts/`.

**Actual location**
![image](https://cloud.githubusercontent.com/assets/196410/8885634/c916b970-321e-11e5-922b-5d560690573a.png)

**Requested location**
![image](https://cloud.githubusercontent.com/assets/196410/8885646/e44b27a8-321e-11e5-9ae6-39c3a88ce65d.png)

**Comment by elidupuis** [comment] 2015-07-27 14:21
Disregard my previous comments. I didn't realize there was a `$icon-font-path` override in our code from our previous set up. :-1: :disappointed:

**Comment by yankeeinlondon** [comment] 2015-11-27 21:27
I'm closing this but if you're still experiencing an issue please let me know

**Closed as completed by yankeeinlondon** 2015-11-27 21:27 UTC
